import "./style.css"
import "./../services/Tires.css"
 export {Header} from "../components/Header/Header"
export {Home} from "../components/Home/Home"

export {DiagnoseFix} from "../services/DiagnoseFix"
export {Prepurches} from "../services/Prepurches"
export {Tires} from "../services/Tires"
export {Login} from "./Login"
export {Regist} from "./Regist"